// Generated from nba_api DraftHistory - the franchise that owned each
// slot (picks 1-48) on draft night, per class. Used by the static logo rail.
export const DRAFT_ORDER: Record<number, Record<number, string>> = {
  "2016": {
    "1": "Philadelphia 76ers",
    "2": "Los Angeles Lakers",
    "3": "Boston Celtics",
    "4": "Phoenix Suns",
    "5": "Minnesota Timberwolves",
    "6": "New Orleans Pelicans",
    "7": "Denver Nuggets",
    "8": "Phoenix Suns",
    "9": "Toronto Raptors",
    "10": "Milwaukee Bucks",
    "11": "Oklahoma City Thunder",
    "12": "Utah Jazz",
    "13": "Sacramento Kings",
    "14": "Chicago Bulls",
    "15": "Denver Nuggets",
    "16": "Boston Celtics",
    "17": "Memphis Grizzlies",
    "18": "Detroit Pistons",
    "19": "Denver Nuggets",
    "20": "Indiana Pacers",
    "21": "Atlanta Hawks",
    "22": "Charlotte Hornets",
    "23": "Boston Celtics",
    "24": "Philadelphia 76ers",
    "25": "LA Clippers",
    "26": "Philadelphia 76ers",
    "27": "Toronto Raptors",
    "28": "Sacramento Kings",
    "29": "San Antonio Spurs",
    "30": "Golden State Warriors",
    "31": "Boston Celtics",
    "32": "Los Angeles Lakers",
    "33": "LA Clippers",
    "34": "Phoenix Suns",
    "35": "Boston Celtics",
    "36": "Milwaukee Bucks",
    "37": "Houston Rockets",
    "38": "Golden State Warriors",
    "39": "New Orleans Pelicans",
    "40": "New Orleans Pelicans",
    "41": "Orlando Magic",
    "42": "Brooklyn Nets",
    "43": "Houston Rockets",
    "44": "Atlanta Hawks",
    "45": "Boston Celtics",
    "46": "Dallas Mavericks",
    "47": "Orlando Magic",
    "48": "Chicago Bulls"
  },
  "2017": {
    "1": "Philadelphia 76ers",
    "2": "Los Angeles Lakers",
    "3": "Boston Celtics",
    "4": "Phoenix Suns",
    "5": "Sacramento Kings",
    "6": "Orlando Magic",
    "7": "Minnesota Timberwolves",
    "8": "New York Knicks",
    "9": "Dallas Mavericks",
    "10": "Sacramento Kings",
    "11": "Charlotte Hornets",
    "12": "Detroit Pistons",
    "13": "Denver Nuggets",
    "14": "Miami Heat",
    "15": "Portland Trail Blazers",
    "16": "Chicago Bulls",
    "17": "Milwaukee Bucks",
    "18": "Indiana Pacers",
    "19": "Atlanta Hawks",
    "20": "Portland Trail Blazers",
    "21": "Oklahoma City Thunder",
    "22": "Brooklyn Nets",
    "23": "Toronto Raptors",
    "24": "Utah Jazz",
    "25": "Orlando Magic",
    "26": "Portland Trail Blazers",
    "27": "Brooklyn Nets",
    "28": "Los Angeles Lakers",
    "29": "San Antonio Spurs",
    "30": "Utah Jazz",
    "31": "Charlotte Hornets",
    "32": "Phoenix Suns",
    "33": "Orlando Magic",
    "34": "Sacramento Kings",
    "35": "Orlando Magic",
    "36": "Philadelphia 76ers",
    "37": "Boston Celtics",
    "38": "Chicago Bulls",
    "39": "Philadelphia 76ers",
    "40": "New Orleans Pelicans",
    "41": "Atlanta Hawks",
    "42": "Utah Jazz",
    "43": "Houston Rockets",
    "44": "New York Knicks",
    "45": "Houston Rockets",
    "46": "Philadelphia 76ers",
    "47": "Indiana Pacers",
    "48": "Milwaukee Bucks"
  },
  "2018": {
    "1": "Phoenix Suns",
    "2": "Sacramento Kings",
    "3": "Atlanta Hawks",
    "4": "Memphis Grizzlies",
    "5": "Dallas Mavericks",
    "6": "Orlando Magic",
    "7": "Chicago Bulls",
    "8": "Cleveland Cavaliers",
    "9": "New York Knicks",
    "10": "Philadelphia 76ers",
    "11": "Charlotte Hornets",
    "12": "LA Clippers",
    "13": "LA Clippers",
    "14": "Denver Nuggets",
    "15": "Washington Wizards",
    "16": "Phoenix Suns",
    "17": "Milwaukee Bucks",
    "18": "San Antonio Spurs",
    "19": "Atlanta Hawks",
    "20": "Minnesota Timberwolves",
    "21": "Utah Jazz",
    "22": "Chicago Bulls",
    "23": "Indiana Pacers",
    "24": "Portland Trail Blazers",
    "25": "Los Angeles Lakers",
    "26": "Philadelphia 76ers",
    "27": "Boston Celtics",
    "28": "Golden State Warriors",
    "29": "Brooklyn Nets",
    "30": "Atlanta Hawks",
    "31": "Phoenix Suns",
    "32": "Memphis Grizzlies",
    "33": "Dallas Mavericks",
    "34": "Atlanta Hawks",
    "35": "Orlando Magic",
    "36": "New York Knicks",
    "37": "Sacramento Kings",
    "38": "Philadelphia 76ers",
    "39": "Philadelphia 76ers",
    "40": "Brooklyn Nets",
    "41": "Orlando Magic",
    "42": "Detroit Pistons",
    "43": "Denver Nuggets",
    "44": "Washington Wizards",
    "45": "Brooklyn Nets",
    "46": "Houston Rockets",
    "47": "Los Angeles Lakers",
    "48": "Minnesota Timberwolves"
  },
  "2019": {
    "1": "New Orleans Pelicans",
    "2": "Memphis Grizzlies",
    "3": "New York Knicks",
    "4": "Los Angeles Lakers",
    "5": "Cleveland Cavaliers",
    "6": "Phoenix Suns",
    "7": "Chicago Bulls",
    "8": "Atlanta Hawks",
    "9": "Washington Wizards",
    "10": "Atlanta Hawks",
    "11": "Minnesota Timberwolves",
    "12": "Charlotte Hornets",
    "13": "Miami Heat",
    "14": "Boston Celtics",
    "15": "Detroit Pistons",
    "16": "Orlando Magic",
    "17": "Brooklyn Nets",
    "18": "Indiana Pacers",
    "19": "San Antonio Spurs",
    "20": "Boston Celtics",
    "21": "Oklahoma City Thunder",
    "22": "Boston Celtics",
    "23": "Utah Jazz",
    "24": "Philadelphia 76ers",
    "25": "Portland Trail Blazers",
    "26": "Cleveland Cavaliers",
    "27": "Brooklyn Nets",
    "28": "Golden State Warriors",
    "29": "San Antonio Spurs",
    "30": "Milwaukee Bucks",
    "31": "Brooklyn Nets",
    "32": "Phoenix Suns",
    "33": "Philadelphia 76ers",
    "34": "Philadelphia 76ers",
    "35": "Atlanta Hawks",
    "36": "Charlotte Hornets",
    "37": "Dallas Mavericks",
    "38": "Chicago Bulls",
    "39": "New Orleans Pelicans",
    "40": "Sacramento Kings",
    "41": "Golden State Warriors",
    "42": "Philadelphia 76ers",
    "43": "Minnesota Timberwolves",
    "44": "Miami Heat",
    "45": "Detroit Pistons",
    "46": "Orlando Magic",
    "47": "Sacramento Kings",
    "48": "LA Clippers"
  },
  "2020": {
    "1": "Minnesota Timberwolves",
    "2": "Golden State Warriors",
    "3": "Charlotte Hornets",
    "4": "Chicago Bulls",
    "5": "Cleveland Cavaliers",
    "6": "Atlanta Hawks",
    "7": "Detroit Pistons",
    "8": "New York Knicks",
    "9": "Washington Wizards",
    "10": "Phoenix Suns",
    "11": "San Antonio Spurs",
    "12": "Sacramento Kings",
    "13": "New Orleans Pelicans",
    "14": "Boston Celtics",
    "15": "Orlando Magic",
    "16": "Portland Trail Blazers",
    "17": "Minnesota Timberwolves",
    "18": "Dallas Mavericks",
    "19": "Brooklyn Nets",
    "20": "Miami Heat",
    "21": "Philadelphia 76ers",
    "22": "Denver Nuggets",
    "23": "New York Knicks",
    "24": "Milwaukee Bucks",
    "25": "Oklahoma City Thunder",
    "26": "Boston Celtics",
    "27": "Utah Jazz",
    "28": "Los Angeles Lakers",
    "29": "Toronto Raptors",
    "30": "Boston Celtics",
    "31": "Dallas Mavericks",
    "32": "Charlotte Hornets",
    "33": "Minnesota Timberwolves",
    "34": "Philadelphia 76ers",
    "35": "Sacramento Kings",
    "36": "Philadelphia 76ers",
    "37": "Washington Wizards",
    "38": "Utah Jazz",
    "39": "New Orleans Pelicans",
    "40": "Memphis Grizzlies",
    "41": "San Antonio Spurs",
    "42": "New Orleans Pelicans",
    "43": "Sacramento Kings",
    "44": "Chicago Bulls",
    "45": "Milwaukee Bucks",
    "46": "Portland Trail Blazers",
    "47": "Boston Celtics",
    "48": "Golden State Warriors"
  },
  "2021": {
    "1": "Detroit Pistons",
    "2": "Houston Rockets",
    "3": "Cleveland Cavaliers",
    "4": "Toronto Raptors",
    "5": "Orlando Magic",
    "6": "Oklahoma City Thunder",
    "7": "Golden State Warriors",
    "8": "Orlando Magic",
    "9": "Sacramento Kings",
    "10": "New Orleans Pelicans",
    "11": "Charlotte Hornets",
    "12": "San Antonio Spurs",
    "13": "Indiana Pacers",
    "14": "Golden State Warriors",
    "15": "Washington Wizards",
    "16": "Oklahoma City Thunder",
    "17": "Memphis Grizzlies",
    "18": "Oklahoma City Thunder",
    "19": "New York Knicks",
    "20": "Atlanta Hawks",
    "21": "New York Knicks",
    "22": "Los Angeles Lakers",
    "23": "Houston Rockets",
    "24": "Houston Rockets",
    "25": "LA Clippers",
    "26": "Denver Nuggets",
    "27": "Brooklyn Nets",
    "28": "Philadelphia 76ers",
    "29": "Phoenix Suns",
    "30": "Utah Jazz",
    "31": "Milwaukee Bucks",
    "32": "New York Knicks",
    "33": "Orlando Magic",
    "34": "Oklahoma City Thunder",
    "35": "New Orleans Pelicans",
    "36": "Oklahoma City Thunder",
    "37": "Detroit Pistons",
    "38": "Chicago Bulls",
    "39": "Sacramento Kings",
    "40": "Sacramento Kings",
    "41": "San Antonio Spurs",
    "42": "Detroit Pistons",
    "43": "New Orleans Pelicans",
    "44": "Brooklyn Nets",
    "45": "Boston Celtics",
    "46": "Toronto Raptors",
    "47": "Toronto Raptors",
    "48": "Atlanta Hawks"
  },
  "2022": {
    "1": "Orlando Magic",
    "2": "Oklahoma City Thunder",
    "3": "Houston Rockets",
    "4": "Sacramento Kings",
    "5": "Detroit Pistons",
    "6": "Indiana Pacers",
    "7": "Portland Trail Blazers",
    "8": "New Orleans Pelicans",
    "9": "San Antonio Spurs",
    "10": "Washington Wizards",
    "11": "New York Knicks",
    "12": "Oklahoma City Thunder",
    "13": "Charlotte Hornets",
    "14": "Cleveland Cavaliers",
    "15": "Charlotte Hornets",
    "16": "Atlanta Hawks",
    "17": "Houston Rockets",
    "18": "Chicago Bulls",
    "19": "Minnesota Timberwolves",
    "20": "San Antonio Spurs",
    "21": "Denver Nuggets",
    "22": "Memphis Grizzlies",
    "23": "Philadelphia 76ers",
    "24": "Milwaukee Bucks",
    "25": "San Antonio Spurs",
    "26": "Dallas Mavericks",
    "27": "Miami Heat",
    "28": "Golden State Warriors",
    "29": "Memphis Grizzlies",
    "30": "Oklahoma City Thunder",
    "31": "Indiana Pacers",
    "32": "Orlando Magic",
    "33": "Toronto Raptors",
    "34": "Oklahoma City Thunder",
    "35": "Los Angeles Lakers",
    "36": "Portland Trail Blazers",
    "37": "Sacramento Kings",
    "38": "San Antonio Spurs",
    "39": "Cleveland Cavaliers",
    "40": "Minnesota Timberwolves",
    "41": "New Orleans Pelicans",
    "42": "New York Knicks",
    "43": "LA Clippers",
    "44": "Atlanta Hawks",
    "45": "Charlotte Hornets",
    "46": "Detroit Pistons",
    "47": "Memphis Grizzlies",
    "48": "Minnesota Timberwolves"
  },
  "2023": {
    "1": "San Antonio Spurs",
    "2": "Charlotte Hornets",
    "3": "Portland Trail Blazers",
    "4": "Houston Rockets",
    "5": "Detroit Pistons",
    "6": "Orlando Magic",
    "7": "Indiana Pacers",
    "8": "Washington Wizards",
    "9": "Utah Jazz",
    "10": "Dallas Mavericks",
    "11": "Orlando Magic",
    "12": "Oklahoma City Thunder",
    "13": "Toronto Raptors",
    "14": "New Orleans Pelicans",
    "15": "Atlanta Hawks",
    "16": "Utah Jazz",
    "17": "Los Angeles Lakers",
    "18": "Miami Heat",
    "19": "Golden State Warriors",
    "20": "Houston Rockets",
    "21": "Brooklyn Nets",
    "22": "Brooklyn Nets",
    "23": "Portland Trail Blazers",
    "24": "Sacramento Kings",
    "25": "Memphis Grizzlies",
    "26": "Indiana Pacers",
    "27": "Charlotte Hornets",
    "28": "Utah Jazz",
    "29": "Indiana Pacers",
    "30": "LA Clippers",
    "31": "Detroit Pistons",
    "32": "Indiana Pacers",
    "33": "San Antonio Spurs",
    "34": "Charlotte Hornets",
    "35": "Boston Celtics",
    "36": "Orlando Magic",
    "37": "Oklahoma City Thunder",
    "38": "Sacramento Kings",
    "39": "Charlotte Hornets",
    "40": "Denver Nuggets",
    "41": "Charlotte Hornets",
    "42": "Washington Wizards",
    "43": "Portland Trail Blazers",
    "44": "San Antonio Spurs",
    "45": "Memphis Grizzlies",
    "46": "Atlanta Hawks",
    "47": "Los Angeles Lakers",
    "48": "LA Clippers"
  },
  "2024": {
    "1": "Atlanta Hawks",
    "2": "Washington Wizards",
    "3": "Houston Rockets",
    "4": "San Antonio Spurs",
    "5": "Detroit Pistons",
    "6": "Charlotte Hornets",
    "7": "Portland Trail Blazers",
    "8": "San Antonio Spurs",
    "9": "Memphis Grizzlies",
    "10": "Utah Jazz",
    "11": "Chicago Bulls",
    "12": "Oklahoma City Thunder",
    "13": "Sacramento Kings",
    "14": "Portland Trail Blazers",
    "15": "Miami Heat",
    "16": "Philadelphia 76ers",
    "17": "Los Angeles Lakers",
    "18": "Orlando Magic",
    "19": "Toronto Raptors",
    "20": "Cleveland Cavaliers",
    "21": "New Orleans Pelicans",
    "22": "Phoenix Suns",
    "23": "Milwaukee Bucks",
    "24": "New York Knicks",
    "25": "New York Knicks",
    "26": "Washington Wizards",
    "27": "Minnesota Timberwolves",
    "28": "Denver Nuggets",
    "29": "Utah Jazz",
    "30": "Boston Celtics",
    "31": "Toronto Raptors",
    "32": "Utah Jazz",
    "33": "Milwaukee Bucks",
    "34": "Portland Trail Blazers",
    "35": "San Antonio Spurs",
    "36": "Indiana Pacers",
    "37": "Minnesota Timberwolves",
    "38": "New York Knicks",
    "39": "Memphis Grizzlies",
    "40": "Portland Trail Blazers",
    "41": "Philadelphia 76ers",
    "42": "Charlotte Hornets",
    "43": "Miami Heat",
    "44": "Houston Rockets",
    "45": "Sacramento Kings",
    "46": "LA Clippers",
    "47": "Orlando Magic",
    "48": "San Antonio Spurs"
  },
  "2025": {
    "1": "Dallas Mavericks",
    "2": "San Antonio Spurs",
    "3": "Philadelphia 76ers",
    "4": "Charlotte Hornets",
    "5": "Utah Jazz",
    "6": "Washington Wizards",
    "7": "New Orleans Pelicans",
    "8": "Brooklyn Nets",
    "9": "Toronto Raptors",
    "10": "Houston Rockets",
    "11": "Portland Trail Blazers",
    "12": "Chicago Bulls",
    "13": "Atlanta Hawks",
    "14": "San Antonio Spurs",
    "15": "Oklahoma City Thunder",
    "16": "Memphis Grizzlies",
    "17": "Minnesota Timberwolves",
    "18": "Washington Wizards",
    "19": "Brooklyn Nets",
    "20": "Miami Heat",
    "21": "Utah Jazz",
    "22": "Atlanta Hawks",
    "23": "New Orleans Pelicans",
    "24": "Oklahoma City Thunder",
    "25": "Orlando Magic",
    "26": "Brooklyn Nets",
    "27": "Brooklyn Nets",
    "28": "Boston Celtics",
    "29": "Phoenix Suns",
    "30": "LA Clippers",
    "31": "Minnesota Timberwolves",
    "32": "Boston Celtics",
    "33": "Charlotte Hornets",
    "34": "Charlotte Hornets",
    "35": "Philadelphia 76ers",
    "36": "Brooklyn Nets",
    "37": "Detroit Pistons",
    "38": "San Antonio Spurs",
    "39": "Toronto Raptors",
    "40": "Washington Wizards",
    "41": "Golden State Warriors",
    "42": "Sacramento Kings",
    "43": "Washington Wizards",
    "44": "Oklahoma City Thunder",
    "45": "Chicago Bulls",
    "46": "Orlando Magic",
    "47": "Milwaukee Bucks",
    "48": "Memphis Grizzlies"
  }
};
