// Generated from nba_api DraftHistory - the franchise that owned each
// first-round slot on draft night, per class. Used by the static logo rail.
export const DRAFT_ORDER: Record<number, Record<number, string>> = {
  "2016": {
    "1": "Philadelphia 76ers",
    "2": "Los Angeles Lakers",
    "3": "Boston Celtics",
    "4": "Phoenix Suns",
    "5": "Minnesota Timberwolves",
    "6": "New Orleans Pelicans",
    "7": "Denver Nuggets",
    "8": "Phoenix Suns",
    "9": "Toronto Raptors",
    "10": "Milwaukee Bucks",
    "11": "Oklahoma City Thunder",
    "12": "Utah Jazz",
    "13": "Sacramento Kings",
    "14": "Chicago Bulls",
    "15": "Denver Nuggets",
    "16": "Boston Celtics",
    "17": "Memphis Grizzlies",
    "18": "Detroit Pistons",
    "19": "Denver Nuggets",
    "20": "Indiana Pacers",
    "21": "Atlanta Hawks",
    "22": "Charlotte Hornets",
    "23": "Boston Celtics",
    "24": "Philadelphia 76ers",
    "25": "LA Clippers",
    "26": "Philadelphia 76ers",
    "27": "Toronto Raptors",
    "28": "Sacramento Kings",
    "29": "San Antonio Spurs",
    "30": "Golden State Warriors"
  },
  "2017": {
    "1": "Philadelphia 76ers",
    "2": "Los Angeles Lakers",
    "3": "Boston Celtics",
    "4": "Phoenix Suns",
    "5": "Sacramento Kings",
    "6": "Orlando Magic",
    "7": "Minnesota Timberwolves",
    "8": "New York Knicks",
    "9": "Dallas Mavericks",
    "10": "Sacramento Kings",
    "11": "Charlotte Hornets",
    "12": "Detroit Pistons",
    "13": "Denver Nuggets",
    "14": "Miami Heat",
    "15": "Portland Trail Blazers",
    "16": "Chicago Bulls",
    "17": "Milwaukee Bucks",
    "18": "Indiana Pacers",
    "19": "Atlanta Hawks",
    "20": "Portland Trail Blazers",
    "21": "Oklahoma City Thunder",
    "22": "Brooklyn Nets",
    "23": "Toronto Raptors",
    "24": "Utah Jazz",
    "25": "Orlando Magic",
    "26": "Portland Trail Blazers",
    "27": "Brooklyn Nets",
    "28": "Los Angeles Lakers",
    "29": "San Antonio Spurs",
    "30": "Utah Jazz"
  },
  "2018": {
    "1": "Phoenix Suns",
    "2": "Sacramento Kings",
    "3": "Atlanta Hawks",
    "4": "Memphis Grizzlies",
    "5": "Dallas Mavericks",
    "6": "Orlando Magic",
    "7": "Chicago Bulls",
    "8": "Cleveland Cavaliers",
    "9": "New York Knicks",
    "10": "Philadelphia 76ers",
    "11": "Charlotte Hornets",
    "12": "LA Clippers",
    "13": "LA Clippers",
    "14": "Denver Nuggets",
    "15": "Washington Wizards",
    "16": "Phoenix Suns",
    "17": "Milwaukee Bucks",
    "18": "San Antonio Spurs",
    "19": "Atlanta Hawks",
    "20": "Minnesota Timberwolves",
    "21": "Utah Jazz",
    "22": "Chicago Bulls",
    "23": "Indiana Pacers",
    "24": "Portland Trail Blazers",
    "25": "Los Angeles Lakers",
    "26": "Philadelphia 76ers",
    "27": "Boston Celtics",
    "28": "Golden State Warriors",
    "29": "Brooklyn Nets",
    "30": "Atlanta Hawks"
  },
  "2019": {
    "1": "New Orleans Pelicans",
    "2": "Memphis Grizzlies",
    "3": "New York Knicks",
    "4": "Los Angeles Lakers",
    "5": "Cleveland Cavaliers",
    "6": "Phoenix Suns",
    "7": "Chicago Bulls",
    "8": "Atlanta Hawks",
    "9": "Washington Wizards",
    "10": "Atlanta Hawks",
    "11": "Minnesota Timberwolves",
    "12": "Charlotte Hornets",
    "13": "Miami Heat",
    "14": "Boston Celtics",
    "15": "Detroit Pistons",
    "16": "Orlando Magic",
    "17": "Brooklyn Nets",
    "18": "Indiana Pacers",
    "19": "San Antonio Spurs",
    "20": "Boston Celtics",
    "21": "Oklahoma City Thunder",
    "22": "Boston Celtics",
    "23": "Utah Jazz",
    "24": "Philadelphia 76ers",
    "25": "Portland Trail Blazers",
    "26": "Cleveland Cavaliers",
    "27": "Brooklyn Nets",
    "28": "Golden State Warriors",
    "29": "San Antonio Spurs",
    "30": "Milwaukee Bucks"
  },
  "2020": {
    "1": "Minnesota Timberwolves",
    "2": "Golden State Warriors",
    "3": "Charlotte Hornets",
    "4": "Chicago Bulls",
    "5": "Cleveland Cavaliers",
    "6": "Atlanta Hawks",
    "7": "Detroit Pistons",
    "8": "New York Knicks",
    "9": "Washington Wizards",
    "10": "Phoenix Suns",
    "11": "San Antonio Spurs",
    "12": "Sacramento Kings",
    "13": "New Orleans Pelicans",
    "14": "Boston Celtics",
    "15": "Orlando Magic",
    "16": "Portland Trail Blazers",
    "17": "Minnesota Timberwolves",
    "18": "Dallas Mavericks",
    "19": "Brooklyn Nets",
    "20": "Miami Heat",
    "21": "Philadelphia 76ers",
    "22": "Denver Nuggets",
    "23": "New York Knicks",
    "24": "Milwaukee Bucks",
    "25": "Oklahoma City Thunder",
    "26": "Boston Celtics",
    "27": "Utah Jazz",
    "28": "Los Angeles Lakers",
    "29": "Toronto Raptors",
    "30": "Boston Celtics"
  },
  "2021": {
    "1": "Detroit Pistons",
    "2": "Houston Rockets",
    "3": "Cleveland Cavaliers",
    "4": "Toronto Raptors",
    "5": "Orlando Magic",
    "6": "Oklahoma City Thunder",
    "7": "Golden State Warriors",
    "8": "Orlando Magic",
    "9": "Sacramento Kings",
    "10": "New Orleans Pelicans",
    "11": "Charlotte Hornets",
    "12": "San Antonio Spurs",
    "13": "Indiana Pacers",
    "14": "Golden State Warriors",
    "15": "Washington Wizards",
    "16": "Oklahoma City Thunder",
    "17": "Memphis Grizzlies",
    "18": "Oklahoma City Thunder",
    "19": "New York Knicks",
    "20": "Atlanta Hawks",
    "21": "New York Knicks",
    "22": "Los Angeles Lakers",
    "23": "Houston Rockets",
    "24": "Houston Rockets",
    "25": "LA Clippers",
    "26": "Denver Nuggets",
    "27": "Brooklyn Nets",
    "28": "Philadelphia 76ers",
    "29": "Phoenix Suns",
    "30": "Utah Jazz"
  },
  "2022": {
    "1": "Orlando Magic",
    "2": "Oklahoma City Thunder",
    "3": "Houston Rockets",
    "4": "Sacramento Kings",
    "5": "Detroit Pistons",
    "6": "Indiana Pacers",
    "7": "Portland Trail Blazers",
    "8": "New Orleans Pelicans",
    "9": "San Antonio Spurs",
    "10": "Washington Wizards",
    "11": "New York Knicks",
    "12": "Oklahoma City Thunder",
    "13": "Charlotte Hornets",
    "14": "Cleveland Cavaliers",
    "15": "Charlotte Hornets",
    "16": "Atlanta Hawks",
    "17": "Houston Rockets",
    "18": "Chicago Bulls",
    "19": "Minnesota Timberwolves",
    "20": "San Antonio Spurs",
    "21": "Denver Nuggets",
    "22": "Memphis Grizzlies",
    "23": "Philadelphia 76ers",
    "24": "Milwaukee Bucks",
    "25": "San Antonio Spurs",
    "26": "Dallas Mavericks",
    "27": "Miami Heat",
    "28": "Golden State Warriors",
    "29": "Memphis Grizzlies",
    "30": "Oklahoma City Thunder"
  },
  "2023": {
    "1": "San Antonio Spurs",
    "2": "Charlotte Hornets",
    "3": "Portland Trail Blazers",
    "4": "Houston Rockets",
    "5": "Detroit Pistons",
    "6": "Orlando Magic",
    "7": "Indiana Pacers",
    "8": "Washington Wizards",
    "9": "Utah Jazz",
    "10": "Dallas Mavericks",
    "11": "Orlando Magic",
    "12": "Oklahoma City Thunder",
    "13": "Toronto Raptors",
    "14": "New Orleans Pelicans",
    "15": "Atlanta Hawks",
    "16": "Utah Jazz",
    "17": "Los Angeles Lakers",
    "18": "Miami Heat",
    "19": "Golden State Warriors",
    "20": "Houston Rockets",
    "21": "Brooklyn Nets",
    "22": "Brooklyn Nets",
    "23": "Portland Trail Blazers",
    "24": "Sacramento Kings",
    "25": "Memphis Grizzlies",
    "26": "Indiana Pacers",
    "27": "Charlotte Hornets",
    "28": "Utah Jazz",
    "29": "Indiana Pacers",
    "30": "LA Clippers"
  },
  "2024": {
    "1": "Atlanta Hawks",
    "2": "Washington Wizards",
    "3": "Houston Rockets",
    "4": "San Antonio Spurs",
    "5": "Detroit Pistons",
    "6": "Charlotte Hornets",
    "7": "Portland Trail Blazers",
    "8": "San Antonio Spurs",
    "9": "Memphis Grizzlies",
    "10": "Utah Jazz",
    "11": "Chicago Bulls",
    "12": "Oklahoma City Thunder",
    "13": "Sacramento Kings",
    "14": "Portland Trail Blazers",
    "15": "Miami Heat",
    "16": "Philadelphia 76ers",
    "17": "Los Angeles Lakers",
    "18": "Orlando Magic",
    "19": "Toronto Raptors",
    "20": "Cleveland Cavaliers",
    "21": "New Orleans Pelicans",
    "22": "Phoenix Suns",
    "23": "Milwaukee Bucks",
    "24": "New York Knicks",
    "25": "New York Knicks",
    "26": "Washington Wizards",
    "27": "Minnesota Timberwolves",
    "28": "Denver Nuggets",
    "29": "Utah Jazz",
    "30": "Boston Celtics"
  },
  "2025": {
    "1": "Dallas Mavericks",
    "2": "San Antonio Spurs",
    "3": "Philadelphia 76ers",
    "4": "Charlotte Hornets",
    "5": "Utah Jazz",
    "6": "Washington Wizards",
    "7": "New Orleans Pelicans",
    "8": "Brooklyn Nets",
    "9": "Toronto Raptors",
    "10": "Houston Rockets",
    "11": "Portland Trail Blazers",
    "12": "Chicago Bulls",
    "13": "Atlanta Hawks",
    "14": "San Antonio Spurs",
    "15": "Oklahoma City Thunder",
    "16": "Memphis Grizzlies",
    "17": "Minnesota Timberwolves",
    "18": "Washington Wizards",
    "19": "Brooklyn Nets",
    "20": "Miami Heat",
    "21": "Utah Jazz",
    "22": "Atlanta Hawks",
    "23": "New Orleans Pelicans",
    "24": "Oklahoma City Thunder",
    "25": "Orlando Magic",
    "26": "Brooklyn Nets",
    "27": "Brooklyn Nets",
    "28": "Boston Celtics",
    "29": "Phoenix Suns",
    "30": "LA Clippers"
  }
};
