// Who owns each 2026 draft slot (post-trade), hand-maintained from the
// current pick-ownership consensus. Full franchise names so the teamColors
// helpers (logo, abbr, accent) resolve.
const PICK_OWNERS_2026: Record<number, string> = {
  1: "Washington Wizards",
  2: "Utah Jazz",
  3: "Memphis Grizzlies",
  4: "Chicago Bulls",
  5: "Los Angeles Clippers",
  6: "Brooklyn Nets",
  7: "Sacramento Kings",
  8: "Atlanta Hawks",
  9: "Dallas Mavericks",
  10: "Milwaukee Bucks",
  11: "Golden State Warriors",
  12: "Oklahoma City Thunder",
  13: "Miami Heat",
  14: "Charlotte Hornets",
  15: "Chicago Bulls",
  16: "Memphis Grizzlies",
  17: "Oklahoma City Thunder",
  18: "Charlotte Hornets",
  19: "Toronto Raptors",
  20: "San Antonio Spurs",
  21: "Detroit Pistons",
  22: "Philadelphia 76ers",
  23: "Atlanta Hawks",
  24: "New York Knicks",
  25: "Los Angeles Lakers",
  26: "Denver Nuggets",
  27: "Boston Celtics",
  28: "Minnesota Timberwolves",
  29: "Cleveland Cavaliers",
  30: "Dallas Mavericks",
  31: "New York Knicks",
  32: "Memphis Grizzlies",
  33: "Brooklyn Nets",
  34: "Sacramento Kings",
  35: "San Antonio Spurs",
  36: "Los Angeles Clippers",
  37: "Oklahoma City Thunder",
  38: "Chicago Bulls",
  39: "Houston Rockets",
  40: "Boston Celtics",
  41: "Miami Heat",
  42: "San Antonio Spurs",
  43: "Brooklyn Nets",
  44: "San Antonio Spurs",
  45: "Sacramento Kings",
  46: "Orlando Magic",
  47: "Phoenix Suns",
  48: "Dallas Mavericks",
  49: "Denver Nuggets",
  50: "Toronto Raptors",
  51: "Washington Wizards",
  52: "Los Angeles Clippers",
  53: "Houston Rockets",
  54: "Golden State Warriors",
  55: "New York Knicks",
  56: "Chicago Bulls",
  57: "Atlanta Hawks",
  58: "New Orleans Pelicans",
  59: "Minnesota Timberwolves",
  60: "Washington Wizards",
};

/** Franchise owning a 2026 draft slot, or null past the second round. */
export function pickOwner2026(slot: number): string | null {
  return PICK_OWNERS_2026[slot] ?? null;
}
